version: "3.9"

services:
  webapp:
    container_name: blogsphere-management-webapp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BLOGSPHERE_API_GATEWAY_BASE_URL: "http://localhost:8000/api/v1"
        BLOGSPHERE_SEARCH_API_BASE_URL: "http://localhost:8000/search"
        BLOGSPHERE_SEARCH_API_SUBSCRIPTION_KEY: "efc2253f-6d87-40bb-9623-88c0e2bbaa4b"
        USE_MOCK_SERVICE: "false"
    ports:
      - "4200:80"
    networks:
      - blogsphere_dev_net


networks:
  blogsphere_dev_net:
    external: true
